import {
  Home,
  KeyRound,
  FileSearch,
  Crown,
  Rocket,
  Users,
  Gem,
  EyeOff,
  Search,
  ListOrdered,
  MessageSquare,
  ShieldCheck,
  MapPin,
  Database,
  Footprints,
  Eye,
  FileText,
  Shield,
  UserCheck,
  HeartHandshake,
  Cpu,
  ShieldAlert,
  Building2,
  Plane,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export const iconMap: Record<string, LucideIcon> = {
  home: Home,
  keyRound: KeyRound,
  fileSearch: FileSearch,
  crown: Crown,
  rocket: Rocket,
  users: Users,
  gem: Gem,
  eyeOff: EyeOff,
  search: Search,
  listOrdered: ListOrdered,
  messageSquare: MessageSquare,
  shieldCheck: ShieldCheck,
  mapPin: MapPin,
  database: Database,
  footprints: Footprints,
  eye: Eye,
  fileText: FileText,
  shield: Shield,
  userCheck: UserCheck,
  heartHandshake: HeartHandshake,
  cpu: Cpu,
  shieldAlert: ShieldAlert,
  building: Building2,
  plane: Plane,
};

export function getIcon(name: string): LucideIcon {
  return iconMap[name] ?? Shield;
}
